name: Build Alpine Base Images
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 1,15 * *"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eightsystems/baseimage-docker
  DOCKER_IMAGE_NAME: 8sistemas/baseimage
jobs:
  build-images:
    runs-on: ubuntu-latest
    if: (!contains(github.event.head_commit.message, '[skipci]') && !contains(github.event.head_commit.message, '[noci]'))
    strategy:
      max-parallel: 2
      matrix:
        alpine: ["3.15", "3.16", "3.20"]
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},${{ env.DOCKER_IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          build-args: |
            BASE_IMAGE=alpine:${{ matrix.alpine }}
            ALPINE_VERSION=${{ matrix.alpine }}
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:alpine-${{ matrix.alpine }},${{ env.DOCKER_IMAGE_NAME }}:alpine-${{ matrix.alpine }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Security Scan against alpine-${{ matrix.alpine }}
        uses: anchore/scan-action@v3
        with:
          image: "ghcr.io/eightsystems/baseimage-docker:alpine-${{ matrix.alpine }}"
          fail-build: false
      - name: Upload Scan Report for alpine-${{ matrix.alpine }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
